### ISSUE TITLE
doesn't support Mac OS X Yosemite

### ISSUE THREAD

**Issue by hanbeibei** [maddingue/Net-Pcap#4]
Hi

the error log is below:
t/17-lib_version.t ......... 1/2 # libpcap version 1.5.3 - Apple version 47

#   Failed test ' - checking version string (libpcap version 1.5.3 - Apple version 47)'
#   at t/17-lib_version.t line 17.
#                   'libpcap version 1.5.3 - Apple version 47'
#     doesn't match '/^libpcap version (?:\d+\.\d+(?:\.\d+|[^\d.\s]+)?|unknown \(pre 0\.8\))$/'
# Looks like you failed 1 test of 2.
t/17-lib_version.t ......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 

which seems that it's very easy to fix, just to modify your match regular expression.

**Comment by sgielen** [comment]
This just bit me too. Regex can be changed to `/^libpcap version (?:\d+.\d+(?:.\d+|[^\d.\s]+)?|unknown (pre 0.8))/` (without the anchoring end `$`) maybe?

**Comment by hanbeibei** [comment]
yes, seems right..

**Comment by hanbeibei** [comment]
I'm reading a very old book: perl network programming, which introduce your module..

**Comment by maddingue** [comment]
Fixed by 25e98f6b141e83b84133b44a67fa4d9c7deebcd8 (merged with b32b086c072f7431bf052fd478b27b1b79298bd7).
