### ISSUE TITLE
Tests fail on OSX Sierra

### ISSUE THREAD

**Issue by preaction** [maddingue/Net-Pcap#8]
I get the following failure when running the tests on OSX Sierra:

```
#   Failed test ' - $err must not be null: syntax error in filter expression: syntax error'
#   at t/09-error.t line 25.
#                   'syntax error in filter expression: syntax error'
#     doesn't match '/^(?:parse|syntax) error$/'
# Looks like you failed 1 test of 10.
```

It appears that libpcap on OSX Sierra has changed the error messages it uses. Ignoring the test failures and installing the module seems to allow it to work correctly.

**Comment by kentfredric** [comment]
This failure is the same on Linux now also.
